import{a as u,S as w,i as d}from"./assets/vendor-BPs2jpei.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api";u.defaults.params={key:"30733650-3915f9571a70fae81f0483ef4"};async function h({page:s=1,per_page:r=20,q:i="cat"}){const{data:o}=await u.get("/",{params:{q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:r}});return o}function f(s){return s.map(({webformatURL:r,largeImageURL:i,tags:o,likes:e,views:t,comments:l,downloads:L})=>`<li class="gallery-item">
    <a class="gallery-link" href="${i}">
      <img
        class="gallery-image"
        src="${r}"
        alt="${o}"
      />
    </a>
    <div class="image-stats">
        <p>Likes <span>${e}</span></p>
        <p>Views <span>${t}</span></p>
        <p>Comments <span>${l}</span></p>
        <p>Downloads <span>${L}</span></p>
    </div>
    </li>`).join("")}const v=document.querySelector(".form"),m=document.querySelector(".gallery"),c=document.querySelector(".loading-text"),n=document.querySelector(".load-more"),g=new w(".gallery a",{captionDelay:250,captionsData:"alt"}),a={page:1,per_page:15,q:"",maxPage:0};v.addEventListener("submit",q);const p={title:"Error",message:"Empty query!",titleColor:"white",messageColor:"white",backgroundColor:"red",position:"topRight"};async function q(s){s.preventDefault();const r=s.currentTarget;if(a.q=r.elements.query.value.trim(),a.q===""){d.show(p);return}a.page=1,m.innerHTML="",c.classList.remove("hidden"),n.classList.add("hidden");try{const{hits:i,totalHits:o}=await h(a);if(o===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");a.maxPage=Math.ceil(o/a.per_page),c.classList.add("hidden"),m.innerHTML=f(i),g.refresh(),a.maxPage>1&&(n.classList.remove("hidden"),n.addEventListener("click",y))}catch(i){d.show({...p,message:i.message}),c.classList.add("hidden")}finally{r.reset()}}async function y(){c.classList.remove("hidden"),n.classList.add("hidden"),a.page+=1;try{const{hits:s}=await h(a);c.classList.add("hidden"),m.insertAdjacentHTML("beforeend",f(s)),g.refresh(),window.scrollBy({top:m.children[0].getBoundingClientRect().height*2,behavior:"smooth"})}catch(s){d.show({...p,message:s.message}),c.classList.add("hidden"),n.classList.add("hidden")}finally{a.page===a.maxPage?(c.classList.add("hidden"),n.classList.add("hidden"),n.removeEventListener("click",y),d.show({...p,message:"We're sorry, but you've reached the end of search results."})):n.classList.remove("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
